apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-service
  namespace: todo-list
  labels:
    app: ping-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ping-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ping-service
    spec:
      hostAliases:
        - ip: "192.168.1.67"
          hostnames:
            - "cob.cobden.net"
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: ping-service
          image: containers.chewed-k8s.net/todo-list/ping-service:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 80
          ports:
            - containerPort: 3000
              name: grpc
            - containerPort: 80
              name: http
          env:
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ping-service-secrets
                  key: vault-token
            - name: MONGO_COLLECTION_PING
              valueFrom:
                secretKeyRef:
                  name: ping-service-secrets
                  key: mongo-ping-collection
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: ping-service-secrets
                  key: mongo-db
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: ping-service-secrets
                  key: mongo-host
            - name: VAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: ping-service-secrets
                  key: vault-host
            - name: MONGO_VAULT_PATH
              valueFrom:
                secretKeyRef:
                  name: ping-service-secrets
                  key: mongo-vault-path

---
apiVersion: v1
kind: Service
metadata:
  name: ping-service
  namespace: todo-list
  labels:
    app: ping-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: grpc
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: ping-service

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ping-service
  namespace: todo-list
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: live-issuer
  labels:
    app: ping-service
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ping.todo-list.app
      secretName: ping-service-tls
  rules:
    - host: ping.todo-list.app
      http:
        paths:
          - path: /v1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: ping-service
                port:
                  number: 80


